### ISSUE TITLE
VR usage data is too general

### ISSUE THREAD

**Issue by RiftFlyer** [X-Plane/dashboard#3]
I realize getting into specific numbers might not be a savvy business decision but could we get better VR usage data. Percentage of users who used VR for the past week or month maybe. 

I don’t believe the current, more general statistic is a useful guide for LR or a fair reflection of the growing uptake amongst simmers.

**Comment by s3cur3** [comment]
I think this is a specific case of the more general feature request to support custom date ranges (#4). Please reopen, though, if I've misunderstood.
